#spring:
#  security:
#    user:
#      name: Vijay
#      password: Vijay123

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-auth
    username: root
    password: Password@321
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
